//import './globals.css'
import { dir } from 'i18next'
import { languages } from '../i18n/settings'

import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter' // or `v14-appRouter` if you are using Next.js v14
import StoreProvider from '../StoreProvider'
import { ThemeProviderContext } from '@/utils/ThemeContext'

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}
export const metadata = {
  title: 'next-mui-kickstarter',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params: { lng } }) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body>
        <StoreProvider>
          <AppRouterCacheProvider>
            <ThemeProviderContext>{children}</ThemeProviderContext>
          </AppRouterCacheProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
